```{r message=FALSE, warning=FALSE, include=FALSE}
# Global Setup
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(fig.path='./figures/', fig.show='asis',  dev = 'png', fig.align='center', out.width = "80%",  out.height = "80%")
knitr::opts_chunk$set(comment = NA)
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(warning = FALSE)
```


```{r eval=FALSE, message=FALSE, warning=FALSE, include=FALSE}

# Load packages
if (!require("knitr")) {install.packages("knitr", dependencies = TRUE)}
library("knitr")
if (!require("rmarkdown")) {install.packages("rmarkdown", dependencies = TRUE)}
library("rmarkdown")
if (!require("ggplot2")) {install.packages("ggplot2", dependencies = TRUE)}
library("ggplot2")
if (!require("reshape2")) {install.packages("reshape2", dependencies = TRUE)}
library("reshape2")
if (!require("grid")) {install.packages("grid", dependencies = TRUE)}
library("grid")
if (!require("scales")) {install.packages("scales", dependencies = TRUE)}
library("scales")
if (!require("iNEXT")) {install.packages("iNEXT", dependencies = TRUE)}
library("iNEXT")
if (!require("readr")) {install.packages("readr", dependencies = TRUE)}
library("readr")
if (!require("funModeling")) {install.packages("funModeling", dependencies = TRUE)}
library("funModeling")
if (!require("dplyr")) {install.packages("dplyr", dependencies = TRUE)}
library("dplyr")
if (!require("vegan")) {install.packages("vegan", dependencies = TRUE)}
library("vegan")
if (!require("factoextra")) {install.packages("factoextra", dependencies = TRUE)}
library("factoextra")
if (!require("FactoMineR")) {install.packages("FactoMineR", dependencies = TRUE)}
library("FactoMineR")
if (!require("NbClust")) {install.packages("NbClust", dependencies = TRUE)}
library("NbClust")
if (!require("cluster")) {install.packages("cluster", dependencies = TRUE)}
library("cluster")
if (!require("ggdendro")) {install.packages("ggdendro", dependencies = TRUE)}
library("ggdendro")
if (!require("kableExtra")) {install.packages("kableExtra", dependencies = TRUE)}
library("kableExtra")
if (!require("tm")) {install.packages("tm", dependencies = TRUE)}
library("tm")
if (!require("SnowballC")) {install.packages("SnowballC", dependencies = TRUE)}
library("SnowballC")
if (!require("wordcloud")) {install.packages("wordcloud", dependencies = TRUE)}
library("wordcloud")
if (!require("htmlwidgets")) {install.packages("htmlwidgets", dependencies = TRUE)}
library("htmlwidgets")
if (!require("wordcloud2")) {install.packages("wordcloud2", dependencies = TRUE)}
library("wordcloud2")
if (!require("RColorBrewer")) {install.packages("RColorBrewer", dependencies = TRUE)}
library("RColorBrewer")
if (!require("servr")) {install.packages("servr", dependencies = TRUE)}
library("servr")
if (!require("bookdownplus")) {install.packages("bookdownplus", dependencies = TRUE)} # For books eg gitbook
library("caTools")
library("bookdownplus")
if (!require("data.table")) {install.packages("data.table", dependencies = TRUE)}
library("data.table")
if (!require("png")) {install.packages("png", dependencies = TRUE)}
library("png")
if (!require("corrplot")) {install.packages("corrplot", dependencies = TRUE)}
library("corrplot")
if (!require("ggpubr")) {install.packages("ggpubr", dependencies = TRUE)} # For pub-ready figs
library("caTools")
library("ggpubr")
if (!require("webshot")) {webshot::install_phantomjs()}
library("webshot")
if (!require("goeveg")) {install.packages("goeveg", dependencies = TRUE)}
library("goeveg")
if (!require("cowplot")) {install.packages("cowplot", dependencies = TRUE)} # For combined plots
library("cowplot")
if (!require("caTools")) {install.packages("caTools", dependencies = TRUE)} # For regression
library("caTools")
if (!require("bookdown")) {install.packages("bookdown", dependencies = TRUE)} # For books
library("bookdown")
# if (!require("devtools")) {install.packages("devtools", dependencies = TRUE)}
# library("devtools")
if (!require("tidyverse")) {install.packages("tidyverse", dependencies = TRUE)}
library("tidyverse")
if (!require("plotrix")) {install.packages("plotrix", dependencies = TRUE)}
library("plotrix")
if (!require("flexdashboard")) {install.packages("flexdashboard", dependencies = TRUE)}
library("flexdashboard")
```


```{r echo=FALSE, message=FALSE, warning=FALSE}
# Global Setup
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(fig.path='./figures/', fig.show='asis',  dev = 'png', fig.align='center', out.width = "80%",  out.height = "80%")
knitr::opts_chunk$set(comment = NA)
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(warning = FALSE)
```


```{r}
library(ggplot2)
library(scales)

# clean ggplot background
cleanup = theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank(), axis.line = element_line(color = "black"))

# multiplot
multiplot <- function(..., plotlist=NULL, file, cols=1, layout=NULL) {

# Make a list from the ... arguments and plotlist
plots <- c(list(...), plotlist)

numPlots = length(plots)

  # If layout is NULL, then use 'cols' to determine layout
  if (is.null(layout)) {
  # Make the panel
  # ncol: Number of columns of plots
  # nrow: Number of rows needed, calculated from # of cols
  layout <- matrix(seq(1, cols * ceiling(numPlots/cols)), ncol = cols, nrow = ceiling(numPlots/cols))}
  if (numPlots==1) {
  print(plots[[1]])
  } else {
  # Set up the page
    grid.newpage()
    pushViewport(viewport(layout = grid.layout(nrow(layout), ncol(layout))))

    # Make each plot, in the correct location
    for (i in 1:numPlots) {
      # Get the i,j matrix positions of the regions that contain this subplot
      matchidx <- as.data.frame(which(layout == i, arr.ind = TRUE))

      print(plots[[i]], vp = viewport(layout.pos.row = matchidx$row,
                                      layout.pos.col = matchidx$col))
    }
  }
}

#################################
library(ggplot2)
library(gridExtra)
library(grid)

bottomsharedlegend <- function(..., nrow = 1, ncol = length(list(...)), position = c("bottom", "right")) {

  plots <- list(...)
  position <- match.arg(position)
  g <- ggplotGrob(plots[[1]] + theme(legend.position = position))$grobs
  legend <- g[[which(sapply(g, function(x) x$name) == "guide-box")]]
  lheight <- sum(legend$height)
  lwidth <- sum(legend$width)
  gl <- lapply(plots, function(x) x + theme(legend.position = "none"))
  gl <- c(gl, nrow = nrow, ncol = ncol)

  combined <- switch(position,
                     "bottom" = arrangeGrob(do.call(arrangeGrob, gl),
                                            legend,
                                            ncol = 1,
                                            heights = unit.c(unit(1, "npc") - lheight, lheight)),
                     "right" = arrangeGrob(do.call(arrangeGrob, gl),
                                           legend,
                                           ncol = 2,
                                           widths = unit.c(unit(1, "npc") - lwidth, lwidth)))
  grid.newpage()
  grid.draw(combined)

}
#################################
rightsharedlegend <- function(..., nrow = 1, ncol = length(list(...)), position = "right") {

  plots <- list(...)
  position <- match.arg(position)
  g <- ggplotGrob(plots[[1]] + theme(legend.position = position))$grobs
  legend <- g[[which(sapply(g, function(x) x$name) == "guide-box")]]
  lheight <- sum(legend$height)
  lwidth <- sum(legend$width)
  gl <- lapply(plots, function(x) x + theme(legend.position = "none"))
  gl <- c(gl, nrow = nrow, ncol = ncol)

  combined <- switch(position,
                     "bottom" = arrangeGrob(do.call(arrangeGrob, gl),
                                            legend,
                                            ncol = 1,
                                            heights = unit.c(unit(1, "npc") - lheight, lheight)),
                     "right" = arrangeGrob(do.call(arrangeGrob, gl),
                                           legend,
                                           ncol = 2,
                                           widths = unit.c(unit(1, "npc") - lwidth, lwidth)))
  grid.newpage()
  grid.draw(combined)

}

#################################

axislayout <- theme(axis.text.x = element_text(size=12,angle = 90, hjust = 0)) +
  theme(axis.text.y = element_text(size=12))+      
  theme(axis.title=element_text(size=14,face="bold"))

mediumaxislayout <- theme(axis.text.x = element_text(size=10,angle = 90, hjust = 0)) +
  theme(axis.text.y = element_text(size=10))+      
  theme(axis.title=element_text(size=14,face="bold"))

mediumaxislayout2 <- theme(axis.text.x = element_text(size=10,angle = 90, hjust = 1)) +
  theme(axis.text.y = element_text(size=10))+      
  theme(axis.title=element_text(size=12,face="bold"))

mediumaxislayout3 <- theme(axis.text.x = element_text(size=10,angle = 0, hjust = 0)) +
  theme(axis.text.y = element_text(size=10))+      
  theme(axis.title=element_text(size=12,face="bold"))

smallaxislayout <- theme(axis.text.x = element_text(size=8,angle = 90, hjust = 0)) +
  theme(axis.text.y = element_text(size=10))+      
  theme(axis.title=element_text(size=12,face="bold"))

smallaxislayout2 <- theme(axis.text.x = element_text(size=8,angle = 90, hjust = 1)) +
  theme(axis.text.y = element_text(size=8))+      
  theme(axis.title=element_text(size=10,face="bold"))

manysampleslayout <- theme(axis.text.x = element_text(size=6,angle = 90, hjust = 0)) +
  theme(axis.text.y = element_text(size=6))+      
  theme(axis.title=element_text(size=10,face="bold"))

normalaxislayout <- theme(axis.text.x = element_text(size=10,angle = 0, hjust = 0)) +
  theme(axis.text.y = element_text(size=10))+ theme(axis.title=element_text(size=12,face="bold"))     

normalaxislayout2 <- theme(axis.text.x = element_text(size=8,angle = 90, hjust = 0)) +
  theme(axis.text.y = element_text(size=10))+ theme(axis.title=element_text(size=12,face="bold"))
     
normalaxislayout3 <- theme(axis.text.x = element_text(size=10,angle = 0, hjust = 0)) +
  theme(axis.text.y = element_text(size=10))+ theme(axis.title=element_text(size=12))

###############################

# scree plot
library(ggplot2)

ggscreeplot <- function(pcobj, type = c('pev', 'cev')) 
{
  type <- match.arg(type)
  d <- pcobj$sdev^2
  yvar <- switch(type, 
                 pev = d / sum(d), 
                 cev = cumsum(d) / sum(d))

  yvar.lab <- switch(type,
                     pev = '% of variance',
                     cev = 'Cumulative % of var')

  df <- data.frame(PC = 1:length(d), yvar = yvar)

  ggplot(data = df, aes(x = PC, y = yvar)) + 
    xlab('Dimensions') + ylab(yvar.lab) +
    geom_point(color="blue", size = 2.5, shape = 18) + geom_path(color="red", size = 1)
}

knitr::opts_chunk$set(echo = FALSE)

###############################

# metacharacters
metaChar = c("$","*","+",".","?","[","^","{","|","(","\\","#")

###############################

italic = theme(axis.text = element_text(face = "italic", size = 12))
xitalic = theme(axis.text.x = element_text(face = "italic", size = 12))
yitalic = theme(axis.text.y = element_text(face = "italic", size = 12))

###############################

rightlegend <- theme(legend.position="right")
bottomlegend <- theme(legend.position="bottom")
leftlegend <- theme(legend.position="left")
nolegend <- theme(legend.position="none")

###############################
xbreaks5 <- scale_x_continuous(labels = comma, breaks=pretty_breaks(n=5))
xbreaks10 <- scale_x_continuous(labels = comma, breaks=pretty_breaks(n=10))
xbreaks15 <- scale_x_continuous(labels = comma, breaks=pretty_breaks(n=15))

ybreaks5 <- scale_y_continuous(labels = comma, breaks=pretty_breaks(n=5))
ybreaks10 <- scale_y_continuous(labels = comma, breaks=pretty_breaks(n=10))
ybreaks15 <- scale_y_continuous(labels = comma, breaks=pretty_breaks(n=15))


###############################
x8y10 <- (theme(axis.text.x = element_text(size = 8))+ theme(axis.text.y = element_text(size = 10)))

x8y10 <- (theme(axis.text.x = element_text(size = 8))+ theme(axis.text.y = element_text(size = 12)))

x10y10 <- (theme(axis.text.x = element_text(size = 10))+ theme(axis.text.y = element_text(size = 10)))

x10y12 <- (theme(axis.text.x = element_text(size = 10))+ theme(axis.text.y = element_text(size = 12)))

x12y12 <- (theme(axis.text.x = element_text(size = 12))+ theme(axis.text.y = element_text(size = 12)))

cex <- par(cex.axis=.8, cex.lab=1, cex.main=1.2, cex.sub=.8)



# #############################

# toSpace <- content_transformer(function (x , pattern ) gsub(pattern, " ", x))


#############################
# mat : is a matrix of data
# ... : further arguments to pass to the native R cor.test function
cor.mtest <- function(mat, ...) {
    mat <- as.matrix(mat)
    n <- ncol(mat)
    p.mat<- matrix(NA, n, n)
    diag(p.mat) <- 0
    for (i in 1:(n - 1)) {
        for (j in (i + 1):n) {
            tmp <- cor.mtest(mat[, i], mat[, j], ...)
            p.mat[i, j] <- p.mat[j, i] <- tmp$p.value
        }
    }
  colnames(p.mat) <- rownames(p.mat) <- colnames(mat)
  p.mat
}


#############################

replaceCommas<-function(x){
  x<-as.numeric(gsub("\\,", "", x))
}


#############################

noxticks <- theme(axis.text.x=element_blank())

noxlabels <- theme(axis.text.x=element_blank())

noxtitle <- theme(axis.title.x=element_blank())

noyticks <- theme(axis.text.y=element_blank())

noylabels <- theme(axis.text.y=element_blank())

noytitle <- theme(axis.title.y=element_blank())


#############################
pco <- function(dis, k=2)
{
        tmp <-cmdscale(dis,k=k,eig=TRUE)
        class(tmp) <- "pco"
        return(tmp)
}


#############################
scaleFUN <- function(x) sprintf("%.0f", x)


#############################

```

